services:
  - type: web
    name: logistica-backend
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn nomeprojeto.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: nomeprojeto.settings
      - key: SECRET_KEY
        value: sua_chave_secreta
      - key: DEBUG
        value: "False"
