# Generated by Django 5.1.6 on 2025-06-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transportador',
            name='capacidade_carga',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
